In [ ]:
# This notebook was created and run in Google Colab: https://colab.research.google.com/drive/1HlIw2FtEZIvHx7wrqt8k5mCw3e8HSnJt?usp=sharing
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score
import pandas as pd
import tensorflow as tf

In [ ]:

url = 'https://raw.githubusercontent.com/rbitas/Stroke-Prediction/main/Data/healthcare-dataset-stroke-data.csv'
df = pd.read_csv(url)

In [ ]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [ ]:
# Generate our categorical variable lists
df_cat = df.dtypes[df.dtypes == "object"].index.tolist()

In [ ]:
# Check the number of unique values in each column
df[df_cat].nunique()

gender            3
ever_married      2
work_type         5
Residence_type    2
smoking_status    4
dtype: int64

In [ ]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(df[df_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names_out(df_cat)
encode_df.head()

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,gender_Female,gender_Male,gender_Other,ever_married_No,ever_married_Yes,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
# Merge one-hot encoded features and drop the originals
df = df.merge(encode_df,left_index=True, right_index=True)
df = df.drop(df_cat,1)
df.head()

<ipython-input-7-1001872591a3>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df = df.drop(df_cat,1)

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke,gender_Female,gender_Male,gender_Other,...,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,9046,67.0,0,1,228.69,36.6,1,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,51676,61.0,0,0,202.21,NaN,1,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,31112,80.0,0,1,105.92,32.5,1,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,60182,49.0,0,0,171.23,34.4,1,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,1665,79.0,1,0,174.12,24.0,1,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
df = df.drop(columns=['id'])

In [ ]:
df.head()

,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke,gender_Female,gender_Male,gender_Other,ever_married_No,...,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,67.0,0,1,228.69,36.6,1,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,61.0,0,0,202.21,NaN,1,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,80.0,0,1,105.92,32.5,1,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,49.0,0,0,171.23,34.4,1,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,79.0,1,0,174.12,24.0,1,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
df['bmi'].min()

10.3

In [ ]:
df['bmi'].max()

97.6

In [ ]:
# Average of the two equals 53.95
df.dtypes

age                               float64
hypertension                        int64
heart_disease                       int64
avg_glucose_level                 float64
bmi                               float64
stroke                              int64
gender_Female                     float64
gender_Male                       float64
gender_Other                      float64
ever_married_No                   float64
ever_married_Yes                  float64
work_type_Govt_job                float64
work_type_Never_worked            float64
work_type_Private                 float64
work_type_Self-employed           float64
work_type_children                float64
Residence_type_Rural              float64
Residence_type_Urban              float64
smoking_status_Unknown            float64
smoking_status_formerly smoked    float64
smoking_status_never smoked       float64
smoking_status_smokes             float64
dtype: object

In [ ]:
df['bmi'] = df['bmi'].fillna(53.95)
df.head()

,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke,gender_Female,gender_Male,gender_Other,ever_married_No,...,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,67.0,0,1,228.69,36.60,1,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,61.0,0,0,202.21,53.95,1,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,80.0,0,1,105.92,32.50,1,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,49.0,0,0,171.23,34.40,1,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,79.0,1,0,174.12,24.00,1,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
# Remove stroke dtarget from features data
y = df.stroke.values
X = df.drop(columns="stroke").values

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, stratify=y)

In [ ]:
# Preprocess numerical data for neural network

# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# Define the deep learning model
nn_model = tf.keras.models.Sequential()
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=21))
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu"))
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=50)

# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/50
120/120 [==============================] - 2s 2ms/step - loss: 0.2273 - accuracy: 0.9512
Epoch 2/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1740 - accuracy: 0.9512
Epoch 3/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1651 - accuracy: 0.9512
Epoch 4/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1603 - accuracy: 0.9512
Epoch 5/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1565 - accuracy: 0.9512
Epoch 6/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1542 - accuracy: 0.9512
Epoch 7/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1522 - accuracy: 0.9512
Epoch 8/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1495 - accuracy: 0.9512
Epoch 9/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1483 - accuracy: 0.9512
Epoch 10/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1471 - accuracy: 0.9512
Epoch 11/50
120/120 [==============================] - 0s 3ms/step - loss: 0.1456 - accuracy: 0.9512
Epoch 12/50
120/120 [==============================] - 0s 3ms/step - loss: 0.1444 - accuracy: 0.9512
Epoch 13/50
120/120 [==============================] - 0s 3ms/step - loss: 0.1439 - accuracy: 0.9512
Epoch 14/50
120/120 [==============================] - 0s 3ms/step - loss: 0.1425 - accuracy: 0.9512
Epoch 15/50
120/120 [==============================] - 0s 3ms/step - loss: 0.1418 - accuracy: 0.9512
Epoch 16/50
120/120 [==============================] - 0s 3ms/step - loss: 0.1413 - accuracy: 0.9512
Epoch 17/50
120/120 [==============================] - 0s 3ms/step - loss: 0.1405 - accuracy: 0.9512
Epoch 18/50
120/120 [==============================] - 0s 3ms/step - loss: 0.1399 - accuracy: 0.9512
Epoch 19/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1395 - accuracy: 0.9512
Epoch 20/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1387 - accuracy: 0.9512
Epoch 21/50
120/120 [==============================] - 1s 5ms/step - loss: 0.1380 - accuracy: 0.9515
Epoch 22/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1375 - accuracy: 0.9515
Epoch 23/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1369 - accuracy: 0.9515
Epoch 24/50
120/120 [==============================] - 1s 6ms/step - loss: 0.1364 - accuracy: 0.9515
Epoch 25/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1358 - accuracy: 0.9520
Epoch 26/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1352 - accuracy: 0.9517
Epoch 27/50
120/120 [==============================] - 1s 5ms/step - loss: 0.1347 - accuracy: 0.9517
Epoch 28/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1341 - accuracy: 0.9530
Epoch 29/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1329 - accuracy: 0.9528
Epoch 30/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1333 - accuracy: 0.9522
Epoch 31/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1326 - accuracy: 0.9538
Epoch 32/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1326 - accuracy: 0.9533
Epoch 33/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1320 - accuracy: 0.9533
Epoch 34/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1311 - accuracy: 0.9533
Epoch 35/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1307 - accuracy: 0.9543
Epoch 36/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1308 - accuracy: 0.9535
Epoch 37/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1300 - accuracy: 0.9546
Epoch 38/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1294 - accuracy: 0.9554
Epoch 39/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1294 - accuracy: 0.9541
Epoch 40/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1289 - accuracy: 0.9551
Epoch 41/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1288 - accuracy: 0.9538
Epoch 42/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1281 - accuracy: 0.9559
Epoch 43/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1279 - accuracy: 0.9549
Epoch 44/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1274 - accuracy: 0.9546
Epoch 45/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1280 - accuracy: 0.9551
Epoch 46/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1272 - accuracy: 0.9551
Epoch 47/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1265 - accuracy: 0.9564
Epoch 48/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1262 - accuracy: 0.9556
Epoch 49/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1260 - accuracy: 0.9572
Epoch 50/50
120/120 [==============================] - 0s 2ms/step - loss: 0.1256 - accuracy: 0.9569
40/40 - 0s - loss: 0.1801 - accuracy: 0.9507 - 209ms/epoch - 5ms/step
Loss: 0.1801377683877945, Accuracy: 0.9507042169570923